"""O2 Exchange SDK for Python.

A complete SDK for trading on the O2 Exchange, a fully on-chain order book
DEX on the Fuel Network.
"""

from .client import O2Client
from .config import Network, NetworkConfig, get_config
from .crypto import (
    EvmWallet,
    Wallet,
    evm_personal_sign,
    fuel_compact_sign,
    generate_evm_keypair,
    generate_evm_wallet,
    generate_keypair,
    generate_wallet,
    load_evm_wallet,
    load_wallet,
    personal_sign,
    raw_sign,
)
from .encoding import (
    GAS_MAX,
    action_to_call,
    build_actions_signing_bytes,
    build_session_signing_bytes,
    encode_identity,
    encode_option_call_data,
    encode_option_none,
    encode_option_some,
    encode_order_args,
    function_selector,
    u64_be,
)
from .errors import (
    AccountNotFound,
    AlreadySubscribed,
    BlockNotFound,
    EventsNotFound,
    GeoRestricted,
    InternalError,
    InvalidAmount,
    InvalidOrderParams,
    InvalidPagination,
    InvalidRequest,
    InvalidSession,
    InvalidSignature,
    InvalidTimeRange,
    InvalidTradeCount,
    MarketAlreadyExists,
    MarketNotFound,
    MarketPaused,
    NoActionsProvided,
    O2Error,
    OnChainRevert,
    OrderNotActive,
    OrderNotFound,
    ParseError,
    RateLimitExceeded,
    SubscriptionError,
    TooManyActions,
    TooManySubscriptions,
    TradeNotFound,
    WhitelistNotConfigured,
)
from .models import (
    AccountCreateResponse,
    AccountInfo,
    ActionsResponse,
    AggregatedAsset,
    Balance,
    BalanceUpdate,
    Bar,
    DepthLevel,
    DepthSnapshot,
    DepthUpdate,
    FaucetResponse,
    Identity,
    Market,
    MarketAsset,
    MarketSummary,
    MarketTicker,
    MarketsResponse,
    NonceUpdate,
    Order,
    OrderBookBalance,
    OrdersResponse,
    OrderUpdate,
    ReferralInfo,
    SessionInfo,
    SessionResponse,
    Trade,
    TradeUpdate,
    WhitelistResponse,
    WithdrawResponse,
)

__all__ = [
    # Client
    "O2Client",
    # Config
    "Network",
    "NetworkConfig",
    "get_config",
    # Crypto
    "Wallet",
    "EvmWallet",
    "generate_keypair",
    "generate_wallet",
    "generate_evm_keypair",
    "generate_evm_wallet",
    "load_wallet",
    "load_evm_wallet",
    "fuel_compact_sign",
    "personal_sign",
    "raw_sign",
    "evm_personal_sign",
    # Encoding
    "u64_be",
    "function_selector",
    "encode_identity",
    "encode_option_none",
    "encode_option_some",
    "encode_option_call_data",
    "encode_order_args",
    "build_session_signing_bytes",
    "build_actions_signing_bytes",
    "action_to_call",
    "GAS_MAX",
    # Errors
    "O2Error",
    "InternalError",
    "InvalidRequest",
    "ParseError",
    "RateLimitExceeded",
    "GeoRestricted",
    "MarketNotFound",
    "MarketPaused",
    "MarketAlreadyExists",
    "OrderNotFound",
    "OrderNotActive",
    "InvalidOrderParams",
    "InvalidSignature",
    "InvalidSession",
    "AccountNotFound",
    "WhitelistNotConfigured",
    "TradeNotFound",
    "InvalidTradeCount",
    "AlreadySubscribed",
    "TooManySubscriptions",
    "SubscriptionError",
    "InvalidAmount",
    "InvalidTimeRange",
    "InvalidPagination",
    "NoActionsProvided",
    "TooManyActions",
    "BlockNotFound",
    "EventsNotFound",
    "OnChainRevert",
    # Models
    "MarketAsset",
    "Market",
    "MarketsResponse",
    "Identity",
    "AccountInfo",
    "AccountCreateResponse",
    "SessionInfo",
    "SessionResponse",
    "Order",
    "OrdersResponse",
    "Trade",
    "OrderBookBalance",
    "Balance",
    "DepthLevel",
    "DepthSnapshot",
    "DepthUpdate",
    "Bar",
    "ActionsResponse",
    "AggregatedAsset",
    "MarketSummary",
    "MarketTicker",
    "OrderUpdate",
    "TradeUpdate",
    "BalanceUpdate",
    "NonceUpdate",
    "WithdrawResponse",
    "WhitelistResponse",
    "ReferralInfo",
    "FaucetResponse",
]
