/**
 * O2 Exchange TypeScript SDK
 *
 * Public API exports for the O2 Exchange SDK.
 *
 * For internal encoding and crypto utilities, import from
 * `@o2exchange/sdk/internals`.
 */

// ── Actions ───────────────────────────────────────────────────────
export {
  type Action,
  cancelOrderAction,
  createOrderAction,
  type MarketActionGroup,
  type Numeric,
  registerRefererAction,
  settleBalanceAction,
} from "./actions.js";

// ── API ───────────────────────────────────────────────────────────
export { O2Api, type O2ApiOptions } from "./api.js";
// ── High-level client ─────────────────────────────────────────────
export {
  type CreateOrderOptions,
  type CreateSessionOptions,
  O2Client,
  type O2ClientOptions,
} from "./client.js";
// ── Config ────────────────────────────────────────────────────────
export {
  DEVNET,
  getNetworkConfig,
  MAINNET,
  Network,
  type NetworkConfig,
  TESTNET,
} from "./config.js";

// ── Crypto (user-facing types) ────────────────────────────────────
export {
  type EvmWallet,
  ExternalEvmSigner,
  ExternalSigner,
  type SignDigestFn,
  type Signer,
  type Wallet,
} from "./crypto.js";

// ── Encoding utilities ────────────────────────────────────────────
export {
  scaleDecimalString,
  scalePriceString,
  validateFractionalPrice,
  validateMinOrder,
} from "./encoding.js";
// ── Errors ────────────────────────────────────────────────────────
export {
  AccountNotFound,
  ActiveSpotOrderLimitExceeded,
  AlreadySubscribed,
  BlockNotFound,
  EventsNotFound,
  GeoRestricted,
  InternalError,
  InvalidAmount,
  InvalidOrderParams,
  InvalidPagination,
  InvalidRequest,
  InvalidSession,
  InvalidSignature,
  InvalidTimeRange,
  InvalidTradeCount,
  InvalidTriggerOrderArgs,
  MarketAlreadyExists,
  MarketNotFound,
  MarketPaused,
  NoActionsProvided,
  O2Error,
  OnChainRevertError,
  OrderNotActive,
  OrderNotFound,
  ParentOrderAlreadyHasFills,
  ParentQuantityMismatch,
  ParseError,
  RateLimitExceeded,
  SessionExpired,
  SubscriptionError,
  TooManyActions,
  TooManySubscriptions,
  TradeNotFound,
  TriggerConflictsWithParent,
  TriggerOrderQuotaExceeded,
  TriggerPairSameDirection,
  WhitelistNotConfigured,
} from "./errors.js";
// ── Models ────────────────────────────────────────────────────────
export type {
  AccountInfo,
  AggregatedAsset,
  AggregatedOrderbook,
  AssetId,
  BalanceResponse,
  BalanceUpdate,
  Bar,
  ContractId,
  CreateAccountResponse,
  DepthChange,
  DepthLevel,
  DepthPrecision,
  DepthSnapshot,
  DepthUpdate,
  FaucetResponse,
  HexId,
  Identity,
  IdentityAddress,
  IdentityContractId,
  Market,
  MarketAsset,
  MarketId,
  MarketRef,
  MarketSummary,
  MarketsResponse,
  MarketTicker,
  NonceUpdate,
  O2ErrorResponse,
  Order,
  OrderBookBalance,
  OrderId,
  OrdersResponse,
  OrderType,
  OrderUpdate,
  PairSummary,
  PairTicker,
  ReferralInfo,
  SessionInfo,
  SessionRequest,
  SessionResponse,
  SessionState,
  Side,
  Signature,
  Trade,
  TradeAccount,
  TradeAccountId,
  TradeUpdate,
  TxId,
  WalletState,
  WhitelistResponse,
  WireOrderType,
  WithdrawRequest,
  WithdrawResponse,
} from "./models.js";
export {
  assetId,
  boundedMarketOrder,
  contractId,
  DepthBook,
  depthPrecision,
  formatPrice,
  formatQuantity,
  hexId,
  identityValue,
  isAddress,
  isContractId,
  limitOrder,
  marketId,
  Nonce,
  orderId,
  SessionActionsResponse,
  scalePriceForMarket,
  scaleQuantityForMarket,
  tradeAccountId,
  txId,
} from "./models.js";
// ── On-chain revert decoding ──────────────────────────────────────
export { augmentRevertReason } from "./onchain-revert.js";
// ── Trigger orders (TP/SL) ────────────────────────────────────────
export {
  type ActiveOrderEntry,
  type ActiveOrdersResponse,
  type ActiveSpotOrder,
  type ActiveTriggerOrder,
  activeTriggerIds,
  ceilToTick,
  floorToTick,
  orderPairByLock,
  PARENT_ORDER_PLACEHOLDER,
  type ParentOrderRef,
  type ProtectionSpec,
  priceTick,
  protectionKind,
  protectionLeg,
  stopLimit,
  stopMarket,
  stopMarketBounded,
  type TriggerOrderArgs,
  type TriggerOrderKind,
  type TriggerQuantity,
  triggerFromParent,
  triggerJudgedPrices,
  triggerKindDiscriminant,
  triggerLeg,
  triggerLockAmount,
  triggerLockPrice,
  triggerQuantity,
  triggerQuantityDiscriminant,
  type WireSide,
  wireSide,
  withTriggerQuantity,
} from "./triggers.js";
// ── Turbo (margin) ────────────────────────────────────────────────
export {
  addCollateralAction,
  addMarginCollateralAction,
  borrowAction,
  buildReferralPayload,
  buildSignedReferralEnvelope,
  closeMarginSessionAction,
  drawAction,
  effectiveBitmap,
  encodeParallelNonce,
  firstFreePosition,
  type Hex,
  isMarginChildAction,
  isMarginPoolAction,
  MARGIN_SESSION_EXPIRY,
  type MarginAction,
  type MarginLimits,
  type MarginStateWire,
  type MarginTierWire,
  type MarginWiring,
  marginActionToCall,
  marginBorrowableBase,
  marginCohortOf,
  marginDrawAmount,
  marginFreezeLine,
  marginLimits,
  marginLiquidationLine,
  marginSellableBase,
  marginSession,
  marginShortableBase,
  type NextMarginAccount,
  type NonceWindow,
  type NonceWindowSlot,
  newMarginAccountNonce,
  type OrderBookCleanup,
  ParallelNonceWindowFull,
  PROLONG_PERIODS,
  type ProlongPeriod,
  prolongPeriodIndex,
  prolongSessionAction,
  registerMarginAccountAction,
  repayAction,
  repayBaseFromCollateralAction,
  repayFromCollateralAction,
  returnQuoteAction,
  revokeMarginAccountSessionAction,
  type SignedEnvelope,
  scaleFor,
  setAutoProlongAction,
  setMarginAccountSessionAction,
  signReferralPayload,
  startMarginSessionAction,
  TurboClient,
  type TurboOpenResult,
  type TurboOrderOptions,
  type TurboPosition,
  type TurboReferralActivation,
  type TurboReferralCode,
  type TurboReferralStatus,
  type TurboSize,
  type TurboSnapshot,
  type TurboWiring,
  u256BE,
  value,
  valueCeil,
  withdrawFromMarginAccountAction,
  withdrawFromMarginAction,
} from "./turbo/index.js";
// ── Utilities ─────────────────────────────────────────────────────
export {
  capitalizeSide,
  ensureNumeric,
  type ResolvedAsset,
  resolveAsset,
  resolveMarket,
  resolveMarketRef,
  scaleNumericPrice,
  scaleOrderType,
} from "./utils.js";
// ── WebSocket ─────────────────────────────────────────────────────
export {
  type ConnectionEvent,
  type ConnectionState,
  O2WebSocket,
  type O2WebSocketOptions,
} from "./websocket.js";
