/**
 * O2 Exchange TypeScript SDK
 *
 * Public API exports for the O2 Exchange SDK.
 */

// ── API ───────────────────────────────────────────────────────────
export { O2Api, type O2ApiOptions } from "./api.js";
// ── High-level client ─────────────────────────────────────────────
export { O2Client, type O2ClientOptions } from "./client.js";
// ── Config ────────────────────────────────────────────────────────
export {
  DEVNET,
  getNetworkConfig,
  MAINNET,
  Network,
  type NetworkConfig,
  TESTNET,
} from "./config.js";
// ── Crypto ────────────────────────────────────────────────────────
export {
  type EvmWallet,
  evmPersonalSign,
  evmWalletFromPrivateKey,
  fuelCompactSign,
  generateEvmWallet,
  generateWallet,
  personalSign,
  rawSign,
  type Wallet,
  walletFromPrivateKey,
} from "./crypto.js";
// ── Encoding ──────────────────────────────────────────────────────
export {
  type ActionJSON,
  actionToCall,
  buildActionsSigningBytes,
  buildSessionSigningBytes,
  buildWithdrawSigningBytes,
  bytesToHex,
  type CancelOrderAction,
  type ContractCall,
  type CreateOrderAction,
  concat,
  encodeIdentity,
  encodeOptionCallData,
  encodeOptionNone,
  encodeOptionSome,
  encodeOrderArgs,
  formatDecimal,
  functionSelector,
  GAS_MAX,
  hexToBytes,
  type MarketInfo,
  type OrderTypeJSON,
  type OrderTypeVariant,
  type RegisterRefererAction,
  type SettleBalanceAction,
  scalePrice,
  scaleQuantity,
  u64BE,
  validateFractionalPrice,
  validateMinOrder,
} from "./encoding.js";
// ── Errors ────────────────────────────────────────────────────────
export {
  AccountNotFound,
  AlreadySubscribed,
  BlockNotFound,
  EventsNotFound,
  GeoRestricted,
  InternalError,
  InvalidAmount,
  InvalidOrderParams,
  InvalidPagination,
  InvalidRequest,
  InvalidSession,
  InvalidSignature,
  InvalidTimeRange,
  InvalidTradeCount,
  isActionsSuccess,
  MarketAlreadyExists,
  MarketNotFound,
  MarketPaused,
  NoActionsProvided,
  O2Error,
  OnChainRevertError,
  OrderNotActive,
  OrderNotFound,
  ParseError,
  parseApiError,
  RateLimitExceeded,
  SessionExpired,
  SubscriptionError,
  TooManyActions,
  TooManySubscriptions,
  TradeNotFound,
  WhitelistNotConfigured,
} from "./errors.js";

// ── Models ────────────────────────────────────────────────────────
export type {
  AccountInfo,
  ActionPayload,
  AggregatedAsset,
  AggregatedOrderbook,
  BalanceResponse,
  BalanceUpdate,
  Bar,
  CancelOrderPayload,
  CreateAccountResponse,
  CreateOrderPayload,
  DepthLevel,
  DepthSnapshot,
  DepthUpdate,
  FaucetResponse,
  Identity,
  IdentityAddress,
  IdentityContractId,
  Market,
  MarketActions,
  MarketAsset,
  MarketSummary,
  MarketsResponse,
  MarketTicker,
  NonceUpdate,
  O2ErrorResponse,
  Order,
  OrderBookBalance,
  OrdersResponse,
  OrderType,
  OrderUpdate,
  PairSummary,
  PairTicker,
  ReferralInfo,
  RegisterRefererPayload,
  Secp256k1Signature,
  SessionActionsRequest,
  SessionActionsResponse,
  SessionInfo,
  SessionRequest,
  SessionResponse,
  SessionState,
  SettleBalancePayload,
  Side,
  Signature,
  Trade,
  TradeAccount,
  TradeUpdate,
  WalletState,
  WhitelistRequest,
  WhitelistResponse,
  WithdrawRequest,
  WithdrawResponse,
} from "./models.js";
export {
  formatPrice,
  formatQuantity,
  identityValue,
  isAddress,
  isContractId,
  scalePriceForMarket,
  scaleQuantityForMarket,
} from "./models.js";
// ── WebSocket ─────────────────────────────────────────────────────
export { O2WebSocket, type O2WebSocketOptions } from "./websocket.js";
